title: Blog of rink1969
description: "Whereof one cannot speak, thereof one must be silent."
author:
  name: "rink1969"
  email: "rink1969@gmail.com"
  url: "https://github.com/rink1969"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "rink1969"
year : "2019"
